/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SetUsernameRouteImport } from './routes/set-username'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheatsheetsRouteImport } from './routes/cheatsheets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheatsheetsIndexRouteImport } from './routes/cheatsheets.index'
import { Route as CheatsheetsCreateRouteImport } from './routes/cheatsheets.create'
import { Route as CheatsheetsIdRouteImport } from './routes/cheatsheets.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SetUsernameRoute = SetUsernameRouteImport.update({
  id: '/set-username',
  path: '/set-username',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetsRoute = CheatsheetsRouteImport.update({
  id: '/cheatsheets',
  path: '/cheatsheets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheatsheetsIndexRoute = CheatsheetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheatsheetsRoute,
} as any)
const CheatsheetsCreateRoute = CheatsheetsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => CheatsheetsRoute,
} as any)
const CheatsheetsIdRoute = CheatsheetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CheatsheetsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cheatsheets': typeof CheatsheetsRouteWithChildren
  '/login': typeof LoginRoute
  '/set-username': typeof SetUsernameRoute
  '/test': typeof TestRoute
  '/cheatsheets/$id': typeof CheatsheetsIdRoute
  '/cheatsheets/create': typeof CheatsheetsCreateRoute
  '/cheatsheets/': typeof CheatsheetsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-username': typeof SetUsernameRoute
  '/test': typeof TestRoute
  '/cheatsheets/$id': typeof CheatsheetsIdRoute
  '/cheatsheets/create': typeof CheatsheetsCreateRoute
  '/cheatsheets': typeof CheatsheetsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cheatsheets': typeof CheatsheetsRouteWithChildren
  '/login': typeof LoginRoute
  '/set-username': typeof SetUsernameRoute
  '/test': typeof TestRoute
  '/cheatsheets/$id': typeof CheatsheetsIdRoute
  '/cheatsheets/create': typeof CheatsheetsCreateRoute
  '/cheatsheets/': typeof CheatsheetsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cheatsheets'
    | '/login'
    | '/set-username'
    | '/test'
    | '/cheatsheets/$id'
    | '/cheatsheets/create'
    | '/cheatsheets/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/set-username'
    | '/test'
    | '/cheatsheets/$id'
    | '/cheatsheets/create'
    | '/cheatsheets'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/cheatsheets'
    | '/login'
    | '/set-username'
    | '/test'
    | '/cheatsheets/$id'
    | '/cheatsheets/create'
    | '/cheatsheets/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheatsheetsRoute: typeof CheatsheetsRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetUsernameRoute: typeof SetUsernameRoute
  TestRoute: typeof TestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-username': {
      id: '/set-username'
      path: '/set-username'
      fullPath: '/set-username'
      preLoaderRoute: typeof SetUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheets': {
      id: '/cheatsheets'
      path: '/cheatsheets'
      fullPath: '/cheatsheets'
      preLoaderRoute: typeof CheatsheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cheatsheets/': {
      id: '/cheatsheets/'
      path: '/'
      fullPath: '/cheatsheets/'
      preLoaderRoute: typeof CheatsheetsIndexRouteImport
      parentRoute: typeof CheatsheetsRoute
    }
    '/cheatsheets/create': {
      id: '/cheatsheets/create'
      path: '/create'
      fullPath: '/cheatsheets/create'
      preLoaderRoute: typeof CheatsheetsCreateRouteImport
      parentRoute: typeof CheatsheetsRoute
    }
    '/cheatsheets/$id': {
      id: '/cheatsheets/$id'
      path: '/$id'
      fullPath: '/cheatsheets/$id'
      preLoaderRoute: typeof CheatsheetsIdRouteImport
      parentRoute: typeof CheatsheetsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheatsheetsRouteChildren {
  CheatsheetsIdRoute: typeof CheatsheetsIdRoute
  CheatsheetsCreateRoute: typeof CheatsheetsCreateRoute
  CheatsheetsIndexRoute: typeof CheatsheetsIndexRoute
}

const CheatsheetsRouteChildren: CheatsheetsRouteChildren = {
  CheatsheetsIdRoute: CheatsheetsIdRoute,
  CheatsheetsCreateRoute: CheatsheetsCreateRoute,
  CheatsheetsIndexRoute: CheatsheetsIndexRoute,
}

const CheatsheetsRouteWithChildren = CheatsheetsRoute._addFileChildren(
  CheatsheetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheatsheetsRoute: CheatsheetsRouteWithChildren,
  LoginRoute: LoginRoute,
  SetUsernameRoute: SetUsernameRoute,
  TestRoute: TestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
