/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SetUsernameRouteImport } from './routes/set-username'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CodicesRouteImport } from './routes/codices'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CodicesIndexRouteImport } from './routes/codices.index'
import { Route as CodicesCreateRouteImport } from './routes/codices.create'
import { Route as CodicesIdRouteImport } from './routes/codices.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SetUsernameRoute = SetUsernameRouteImport.update({
  id: '/set-username',
  path: '/set-username',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CodicesRoute = CodicesRouteImport.update({
  id: '/codices',
  path: '/codices',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CodicesIndexRoute = CodicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CodicesRoute,
} as any)
const CodicesCreateRoute = CodicesCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => CodicesRoute,
} as any)
const CodicesIdRoute = CodicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CodicesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/codices': typeof CodicesRouteWithChildren
  '/login': typeof LoginRoute
  '/set-username': typeof SetUsernameRoute
  '/test': typeof TestRoute
  '/codices/$id': typeof CodicesIdRoute
  '/codices/create': typeof CodicesCreateRoute
  '/codices/': typeof CodicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/set-username': typeof SetUsernameRoute
  '/test': typeof TestRoute
  '/codices/$id': typeof CodicesIdRoute
  '/codices/create': typeof CodicesCreateRoute
  '/codices': typeof CodicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/codices': typeof CodicesRouteWithChildren
  '/login': typeof LoginRoute
  '/set-username': typeof SetUsernameRoute
  '/test': typeof TestRoute
  '/codices/$id': typeof CodicesIdRoute
  '/codices/create': typeof CodicesCreateRoute
  '/codices/': typeof CodicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/codices'
    | '/login'
    | '/set-username'
    | '/test'
    | '/codices/$id'
    | '/codices/create'
    | '/codices/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/set-username'
    | '/test'
    | '/codices/$id'
    | '/codices/create'
    | '/codices'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/codices'
    | '/login'
    | '/set-username'
    | '/test'
    | '/codices/$id'
    | '/codices/create'
    | '/codices/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodicesRoute: typeof CodicesRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetUsernameRoute: typeof SetUsernameRoute
  TestRoute: typeof TestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-username': {
      id: '/set-username'
      path: '/set-username'
      fullPath: '/set-username'
      preLoaderRoute: typeof SetUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codices': {
      id: '/codices'
      path: '/codices'
      fullPath: '/codices'
      preLoaderRoute: typeof CodicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codices/': {
      id: '/codices/'
      path: '/'
      fullPath: '/codices/'
      preLoaderRoute: typeof CodicesIndexRouteImport
      parentRoute: typeof CodicesRoute
    }
    '/codices/create': {
      id: '/codices/create'
      path: '/create'
      fullPath: '/codices/create'
      preLoaderRoute: typeof CodicesCreateRouteImport
      parentRoute: typeof CodicesRoute
    }
    '/codices/$id': {
      id: '/codices/$id'
      path: '/$id'
      fullPath: '/codices/$id'
      preLoaderRoute: typeof CodicesIdRouteImport
      parentRoute: typeof CodicesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CodicesRouteChildren {
  CodicesIdRoute: typeof CodicesIdRoute
  CodicesCreateRoute: typeof CodicesCreateRoute
  CodicesIndexRoute: typeof CodicesIndexRoute
}

const CodicesRouteChildren: CodicesRouteChildren = {
  CodicesIdRoute: CodicesIdRoute,
  CodicesCreateRoute: CodicesCreateRoute,
  CodicesIndexRoute: CodicesIndexRoute,
}

const CodicesRouteWithChildren =
  CodicesRoute._addFileChildren(CodicesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodicesRoute: CodicesRouteWithChildren,
  LoginRoute: LoginRoute,
  SetUsernameRoute: SetUsernameRoute,
  TestRoute: TestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
